stages:
  - build
  - test

build website:
  stage: build  # build job
  image: node
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
  artifacts:
    paths:
      - ./public

test artifact:
  stage: test # test job
  script:
    - grep "Gatsby" ./public/index.html
    - grep "XXXXXXXX" ./public/index.html